// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9NG45aAgQFuAj8OK7dlSqIOORkjIgZyw',
    appId: '1:799408216186:web:76c367772318063a2743c3',
    messagingSenderId: '799408216186',
    projectId: 'mostlynotes-maybefitness',
    authDomain: 'mostlynotes-maybefitness.firebaseapp.com',
    storageBucket: 'mostlynotes-maybefitness.appspot.com',
    measurementId: 'G-JCWES8HB58',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0mET2B7rBiXhvO32V3RnjZixw7F3s7pc',
    appId: '1:799408216186:android:eaa2b72925c86ae72743c3',
    messagingSenderId: '799408216186',
    projectId: 'mostlynotes-maybefitness',
    storageBucket: 'mostlynotes-maybefitness.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCa5N9ynOp-jFVpMyKUv2gzZwboOCphjZ4',
    appId: '1:799408216186:ios:0a9a0b3365bc386b2743c3',
    messagingSenderId: '799408216186',
    projectId: 'mostlynotes-maybefitness',
    storageBucket: 'mostlynotes-maybefitness.appspot.com',
    iosBundleId: 'com.example.firstFlutterProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCa5N9ynOp-jFVpMyKUv2gzZwboOCphjZ4',
    appId: '1:799408216186:ios:b0ac6acc67a064792743c3',
    messagingSenderId: '799408216186',
    projectId: 'mostlynotes-maybefitness',
    storageBucket: 'mostlynotes-maybefitness.appspot.com',
    iosBundleId: 'com.example.firstFlutterProject.RunnerTests',
  );
}
